title: Blogatto
description: A Gleam framework for building static blogs with Lustre and Markdown
theme: minima
image: /og_preview.jpeg
github_username: veeso
codeberg_url: https://codeberg.org/veeso/blogatto
