name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        with:
          otp-version: "28"
          gleam-version: "1.17.0"
          rebar3-version: "3"
          # elixir-version: "1"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
      - name: build example
        run: |
          cd examples/simple_blog
          gleam run
